apiVersion: v1
kind: Service
metadata:
  name: train-booking-service
  namespace: train-system
spec:
  selector:
    app: train-booking
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30002
